### ISSUE TITLE
problems in running visual studio plugin

### ISSUE THREAD

**Issue by alonye** [getgauge/gauge-csharp#149] opened 2018-08-22 12:20 UTC
Hello!
i posted another issue just a minute ago.
I'm having trouble with the VS plugin.
I click tools -> extensions and updates -> online -> type "gauge" -> download and install **Gauge plugin for Visual Studio**.
after restarting VS I get this window:
![image](https://user-images.githubusercontent.com/42608971/44462896-a9a20f00-a61e-11e8-840e-8afde57e8d73.png)

Then, when I click  File -> New -> Project and choose: Installed -> Templates -> Visual C# -> Windows -> Test:
I can see Unit Test Project only.  
I should see: Gauge Test Project

What do I need to do to open a gauge project?
Thanks!
### Gauge version
```
Gauge version: 1.0.0
Commit Hash: 5a99965

Plugins
-------
csharp (0.10.4)
html-report (4.0.5)
screenshot (0.0.1)
```

**Comment by alonye** [comment] 2018-08-26 09:06
Hi,
Thank you for your answer.
After downloading the file from the link you provided, i tried to install it and got the message:
![image](https://user-images.githubusercontent.com/42608971/44626596-b4fb8000-a927-11e8-8fa5-2cb686c25f64.png)

When I click view install log, I get this file:
[VSIXInstaller_297cd4d2-7b3f-49c3-803a-626ba6e217b6.log](https://github.com/getgauge/gauge-csharp/files/2321379/VSIXInstaller_297cd4d2-7b3f-49c3-803a-626ba6e217b6.log)

As fot the This is the ActivityLog.xml file:
[ActivityLog.log](https://github.com/getgauge/gauge-csharp/files/2321381/ActivityLog.log)

**Comment by sriv** [comment] 2018-08-27 06:07
what version of visual studio are you getting this error?

**Comment by alonye** [comment] 2018-08-27 06:11
2017 community

**Comment by sriv** [comment] 2018-08-27 06:28
Sorry, I thought you were on VS2015, since your original post's path indicated this structure : `...VisualStudio\14.0\...`. `14.0` is the version for VS2015.

I will investigate this on vs2017 in some time, I don't have windows at the moment. 

The Gauge Templates are available only for vs2015. We will make a release supporting VS2017 soon. 

If you can, could you check running this on VS2015? That's help isolate the cause of the problem. Thanks.

**Comment by sguptatw** [comment] 2018-08-27 06:45
The template for VS 2017 issue can be tracked as a part of templates issue is tracked via https://github.com/getgauge-contrib/gauge-visualstudio-templates/issues/1

**Comment by Apoorva-GA** [comment] 2019-08-12 10:29
Should be fixed as part of https://github.com/getgauge-contrib/gauge-visualstudio-templates/issues/1

**Comment by Debashis9012** [comment] 2019-08-20 10:30
This issue has been verified and found fixed.

**Closed by Debashis9012** 2019-08-20 10:30 UTC
