### ISSUE TITLE
Connection is closed after long step (~200s)

### ISSUE THREAD

**Issue by ludekcakl** [getgauge/gauge-csharp#92] opened 2016-08-19 11:48 UTC
### Steps to reproduce
- create step with wait implementation:
```
        [Step("Wait for <secconds> secconds")]
        public static void Wait(int secconds)
        {
            Thread.Sleep(TimeSpan.FromSeconds(secconds));
        }
```

- run steps with increasing wait time. Gauge will fail with:
```
Gauge.CSharp.Runner.SandboxBuilder Creating a Sandbox in: C:\Projects\NBS\src\Acc.Tests\Acc.Gui.Tests\bin\Debug\
Checking updates...
Sandbox Loaded Instance Manager of Type:Gauge.CSharp.Lib.DefaultClassInstanceManager
Executing in 1 parallel streams.
[runner: 1] Gauge.CSharp.Runner.SandboxBuilder Creating a Sandbox in: C:\Projects\NBS\src\Acc.Tests\Acc.Gui.Tests\bin\Debug\[runner: 1]
[runner: 1] Sandbox Loaded Instance Manager of Type:Gauge.CSharp.Lib.DefaultClassInstanceManager[runner: 1]
[runner: 1] # Wait test
[runner: 1] Sandbox Acc.Gui.Tests.Implementation.Shared[runner: 1]
[runner: 1] Starting ChromeDriver 2.23.409699 (49b0fa931cda1caad0ae15b7d1b68004acd05129) on port 61395
Only local connections are allowed.
[runner: 1]   ## Waitings
[runner: 1]       * Wait for "100" secconds
[runner: 1] Sandbox Acc.Gui.Tests.Implementation.Shared[runner: 1]
[runner: 1]       * Wait for "150" secconds
[runner: 1] Sandbox Acc.Gui.Tests.Implementation.Shared[runner: 1]
[runner: 1]       * Wait for "200" secconds
[runner: 1] Sandbox Acc.Gui.Tests.Implementation.Shared[runner: 1]
[runner: 1]       * Wait for "250" secconds
[runner: 1]
        Failed Step: Wait for "250" secconds
        Specification: Acc.Gui.Tests\Specs\Settlement\Wait.spec:9
        Error Message: Connection closed [127.0.0.1:61394] cause: EOF
        Stacktrace:

[runner: 1]         Error Message: write tcp 127.0.0.1:61392->127.0.0.1:61394: use of closed network connection
        Stacktrace:

[runner: 1]     Error Message: write tcp 127.0.0.1:61392->127.0.0.1:61394: use of closed network connection
    Stacktrace:

[runner: 1]   Error Message: write tcp 127.0.0.1:61392->127.0.0.1:61394: use of closed network connection
  Stacktrace:

[runner: 1]
[runner: 1] Gauge.CSharp.Runner.GaugeListener System.Runtime.Remoting.RemotingException: Object '/06fbe031_26cd_443f_852b_923e7dc21366[runner: 1] vyb5sepifie83_12.rem' has been disconnected or does not exist at the server.[runner: 1]
[runner: 1]
[runner: 1] Server stack trace: [runner: 1]
[runner: 1]    at System.Runtime.Remoting.Channels.ChannelServices.CheckDisconnectedOrCreateWellKnownObject(IMessage msg)[runner: 1]
[runner: 1]    at System.Runtime.Remoting.Channels.ChannelServices.SyncDispatchMessage(IMessage msg)[runner: 1]
[runner: 1]
[runner: 1] Exception rethrown at [0]: [runner: 1]
[runner: 1]    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)[runner: 1]
[runner: 1]    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)[runner: 1]
[runner: 1]    at Gauge.CSharp.Runner.Models.GaugeMethod.get_ParameterCount()[runner: 1]
[runner: 1]    at Gauge.CSharp.Runner.Processors.ExecuteStepProcessor.Process(Message request) in c:\Program Files (x86)\Go Agent\pipe[runner: 1] -Package\gauge-csharp\Runner\Processors\ExecuteStepProcessor.cs:line 49[runner: 1]
[runner: 1]    at Gauge.CSharp.Runner.GaugeListener.PollForMessages() in c:\Program Files (x86)\Go Agent\pipelines\Csharp-Package\gauge-csharp\Runner\GaugeListener.cs:line 52[runner: 1]
  Error Message: write tcp 127.0.0.1:61392->127.0.0.1:61394: use of closed network connection
```

### Gauge version
```
Gauge version: 0.6.1

Plugins
-------
csharp (0.9.1)
html-report (2.1.1)
xml-report (0.1.3)
```

**Comment by Buthrakaur** [comment] 2016-08-24 11:03
Hello @sriv ,
this issue is probably the root cause of errors I already discussed with you on gitter few weeks ago. I reported the same exceptions being thrown on TeamCity agents and you suggested it's caused by some firewall or antivirus, but I was probably also facing the problem of long step execution duration. Is it possible to increase the timeout or rather make the timeout configurable, please?

**Comment by sriv** [comment] 2016-08-26 04:34
I can reproduce this. Thanks for the steps @ludekcakl .

I was under the assumption that @hakito's [commit](https://github.com/getgauge/gauge-csharp/commit/9a36196781b766d715f5c78748c044843ae34935) would address this, but for some reason it doesn't. 

Need to investigate this further.

@Buthrakaur - this isn't the runner timing out, but it is the runner's sandbox timing out :(, which is internal to Gauge-CSharp and should not have to be visible to the user. Apologies if I misdirected you on your earlier comment.

**Comment by sguptatw** [comment] 2016-08-30 03:05
Tested with the following spec and works fine.

```
Wait for specified time to execute
=====================

     |sleepTime|
     |---------|
     |100      |
     |1000     |
     |4000     |
     |10000    |

* Wait for <sleepTime> to execute

With long Steps1
---------------
* Wait for <sleepTime> to execute

With long Steps2
---------------
* Wait for <sleepTime> to execute

With long Steps3
---------------
* Wait for <sleepTime> to execute

With long Steps4
---------------
* Wait for <sleepTime> to execute

With long Steps5
---------------
* Wait for <sleepTime> to execute

With long Steps6
---------------
* Wait for "10000" to execute
________________________________________________

* Wait for <sleepTime> to execute
```

**Comment by sguptatw** [comment] 2016-08-30 03:12
Tested with time wait in concepts

Concept
```
# Wait for <sleepTime> to execute cpt
* Wait for <sleepTime> to execute
```

Spec
```
With Long Steps
===============

     |sleepTime|
     |---------|
     |100      |
     |1000     |
     |4000     |
     |10000    |

* Wait for <sleepTime> to execute cpt

With long Steps1
---------------
* Wait for <sleepTime> to execute cpt

With long Steps2
---------------
* Wait for <sleepTime> to execute cpt

With long Steps3
---------------
* Wait for <sleepTime> to execute cpt

With long Steps4
---------------
* Wait for <sleepTime> to execute cpt

With long Steps5
---------------
* Wait for <sleepTime> to execute cpt

With long Steps6
---------------
* Wait for "10000" to execute cpt
```

**Comment by Buthrakaur** [comment] 2016-08-31 11:07
Hi @sriv , how is it going with this issue? I don't understand the QA "roundtrip" and it also looks like the 0.9.2 version containing your fix for this issue is broken with some errors from travis and appveyor builds...

**Comment by sriv** [comment] 2016-09-01 03:09
Hi @Buthrakaur - the QA roundtrip is just for us in the team to track issues - @sguptatw was looking at various use cases to see if this issue is unresolved in any scenario. Her case is that when using concepts with table driven execution, the issue is persistent. I am unable to replicate it, hence the back and forth.

@sguptatw: I tried [this project](https://gist.github.com/sriv/b9f088a03ec4499fda3b57a008da09da), output is in the gist. Could you please share a project that I can replicate the issue on?

Note that the whole run took about 1hr20mins, and the execution passed without failure.


@Buthrakaur: on your point about failed appveyor and travis builds, I believe those are failures independant of this fix. The two tests that are failing are features that are yet to be implemented in gauge core. I need to fix the tagging of tests<->app to have appropriate version of tests running against the app.

**Comment by Buthrakaur** [comment] 2016-09-07 11:21
Hi @sriv , any progress? We're blocked by this issue at the moment :(

**Comment by sriv** [comment] 2016-09-12 12:48
@Buthrakaur , @ludekcakl - the fix is available in the [latest nightly version](https://bintray.com/gauge/gauge-csharp/Nightly/_latestVersion) of gauge-csharp. Could you please try this out and see if it fixes your cases?

**Comment by Buthrakaur** [comment] 2016-09-13 09:46
I just tried it on the original timeout test provided by @ludekcakl and it looks ok:
```
Gauge version: 0.6.1

Plugins
-------
csharp (0.9.2.nightly-2016-09-12)
html-report (2.1.1)
xml-report (0.1.3)
Gauge.CSharp.Runner.SandboxBuilder Creating a Sandbox in: C:\Temp\Acc.Tests\bin\Debug
Checking updates...
Sandbox Loaded Instance Manager of Type:Gauge.CSharp.Lib.DefaultClassInstanceManager
Executing in 1 parallel streams.
[runner: 1] Gauge.CSharp.Runner.SandboxBuilder Creating a Sandbox in: C:\Temp\Acc.Tests\bin\Debug[runner: 1]
[runner: 1] Sandbox Loaded Instance Manager of Type:Gauge.CSharp.Lib.DefaultClassInstanceManager[runner: 1]
[runner: 1] # timeout test
[runner: 1] Sandbox Acc.Tests.Implementation.Shared[runner: 1]
[runner: 1]   ## tst
[runner: 1]       * Wait for "100" seconds
[runner: 1] Sandbox Acc.Tests.Implementation.Shared[runner: 1]
[runner: 1]       * Wait for "250" seconds
[runner: 1] Sandbox Acc.Tests.Implementation.Shared[runner: 1]
[runner: 1]       * Wait for "500" seconds
[runner: 1] Sandbox Acc.Tests.Implementation.Shared[runner: 1]
[runner: 1]
Sucessfully generated xml-report to => C:\Temp\Acc.Tests\reports\xml-report
Plugin [Xml Report] with pid [16308] has exited
Successfully generated html-report to => C:\Temp\Acc.Tests\reports\html-report
Plugin [Html Report] with pid [18616] has exited
Specifications: 1 executed      1 passed        0 failed        0 skipped
Scenarios:      1 executed      1 passed        0 failed        0 skipped

Total time taken: 14m15.045s
```

I'll try it on our real tests too and report back.

**Comment by Buthrakaur** [comment] 2016-09-13 10:40
I just tried on our real test suite which suffered by the timeout issue before and it seems to work just fine with the 0.9.2 nightly build. So could you release 0.9.2 as a regular version? I'll use `--install csharp --file gauge-csharp-0.9.2.nightly-2016-09-12.zip` in the meantime.

**Comment by sriv** [comment] 2016-09-13 10:53
@Buthrakaur - neat! I will work on releasing 0.9.2, but it requires some cleanup in our build scripts and tests. Am working on that at the moment.

**Comment by sriv** [comment] 2016-09-14 10:37
Gauge-C# 0.9.2 is now released and should have this fix.

**Closed** 2016-09-14 10:37 UTC
Labels: bug, in progress
