### ISSUE TITLE
While Invoking API or Dlls Methods through Gauge Csharp, Gauge gives System.IO.FileLoadException

### ISSUE THREAD

**Issue by somnath4993** [getgauge/gauge-csharp#37] opened 2015-09-16 13:21 UTC
![newerroroccurewithgauge](https://cloud.githubusercontent.com/assets/14311712/9905665/e77bfc40-5ca3-11e5-91bd-6f6df03f5f38.PNG)

**Comment by sriv** [comment] 2015-09-17 05:29
There are a couple of things to check here:

- Your build log prints a warning saying "Found conflicts between different version of the same assembly". You may want to check that.
- The exception that you see is thrown by the .NET CAS. This usually happens if you are using a mapped network drive or an UNC location.

If you an share a sample project simulating this, or highlight steps for us to replicate, that would be great.

**Comment by somnath4993** [comment] 2015-09-17 12:46
Hi,

Thanks for reply!!!

But same dlls working fine with specflow.

**Comment by alexbestul** [comment] 2016-02-22 20:30
I ran into a similar issue with one of my projects.  There were assembly version conflicts that caused the Gauge runner to crash, very painfully.  The same project (a WCF service) would build and run in IIS, and would also build and run in Microsoft VisualStudio TestTools unit tests.

I suspect that the problem is with one of:

* The Gauge runner is more strict about assembly binding than other execution environments (I'm not sure if this is actually possible--it's just a theory)
* The Gauge runner is not honoring assembly binding redirection
* There is some issue related to the way Gauge collects dependencies into the gauge-bin directory.

I ended up eliminating the assemblies that were causing conflicts in my case, so I didn't dig very deep into the issue.  If you're interested, I can try to assemble a sample project.

**Comment by Buthrakaur** [comment] 2016-05-27 13:46
Hi @sriv , I think the assembly redirect issue still isn't solved in 0.7.2 version. We just upgraded Oracle DB driver, but need to use assembly redirect because of some library which depends on older driver version. The library references version 4.121.1.0. We upgraded to 4.121.2.0 version and used this assembly redirect, which works in all other our apps except Gauge tests:
```
      <dependentAssembly>
        <publisherPolicy apply="no" />
        <assemblyIdentity name="Oracle.ManagedDataAccess" publicKeyToken="89b483f429c47342" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.121.2.0" newVersion="4.121.2.0" />
      </dependentAssembly>    
```
I'm getting this exception when I run Gauge tests:
```
Error Message: Could not load file or assembly 'Oracle.ManagedDataAccess, Version=4.121.1.0, Culture=neutral, PublicKeyToken=89b483f429c47342' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

`gauge -version`:
```
Gauge version: 0.4.0

Plugins
-------
csharp (0.7.2)
html-report (2.1.0)
xml-report (0.1.2)
```

**Comment by sriv** [comment] 2016-05-30 09:40
Yes, I can replicate this. WIll try to get to the root of this.

**Comment by sriv** [comment] 2016-06-23 05:26
The [newest release](https://github.com/getgauge/gauge-csharp/releases/tag/v0.8.0) contains some fixes for loading assemblies and dependencies. This issue should be fixed. @alexbestul / @Buthrakaur - can you please check if this works?

**Closed** 2017-04-12 02:20 UTC
