### ISSUE TITLE
allow more than one step attribute on a method

### ISSUE THREAD

**Issue by MattFenner** [getgauge/gauge-csharp#42] opened 2015-11-17 09:00 UTC
I see that the step attribute takes multiple strings to describe the matching text. however is there any reason you don't just allow multiple occurances of the step attribute? seems like it would be neater.

obviously just an enhancement not a bug.

e.g.
```
        [Step("Take a memory benchmark",
              "Take another memory benchmark")]
        public void TakeAMemoryBenchmark()
        {
            //take benchmark and add it to the stack of benchmarks
        }
```

could be:
```
        [Step("Take a memory benchmark")]
        [Step("Take another memory benchmark")]
        public void TakeAMemoryBenchmark()
        {
            //take benchmark and add it to the stack of benchmarks
        }
```

**Comment by sriv** [comment] 2015-11-17 10:11
Although this is the default behaviour of a Custom Attribute in C#, this is by design in this case. The multiple parameters in a Step text are assumed to be aliases, i.e. different words in step texts mapping to a single implementation (exactly as you describe in the example here).

There is an implicit Gauge contract assumption here: Every method/function with a `Step` attribute, is assumed to be an implementation of the `Step`. What this means is that, the number and order of parameters have to be consistent across the step texts, and this implementation is the result of taking a design call that there will be just one Step attribute per method, but you can overload it with aliases. While this isn't a technical enforcement, it seems that the likelihood to miss this convention would be higher, while allowing multiple step annotations.

**Comment by MattFenner** [comment] 2015-11-18 00:41
Fair enough if it is a design decision, i can see pros and cons either way so i just thought i would raise it as food for thought.

keep in mind SpecFlow allows you to have multiple instances of the same attribute in the way i am describing. see http://www.specflow.org/documentation/Step-Definitions/ so it is something that can work.

**Comment by sriv** [comment] 2016-03-01 05:30
We would like to leave this as it is, i.e. have multiple aliases in a single step attribute. Closing this issue.

**Closed by sriv** 2016-03-01 05:30 UTC
